/*
    Strings for ipc
*/
export const FOLDER_OPEN_IPC = 'FOLDER_OPEN_IPC';
export const FOLDER_SELECT_IPC = 'FOLDER_SELECT_IPC';
export const FOLDER_SELECTED_IPC = 'FOLDER_SELECTED_IPC';
export const FILE_OPEN_IPC = 'FILE_OPEN_IPC';
export const FILE_SELECT_IPC = 'FILE_SELECT_IPC';
export const FILE_SELECTED_IPC = 'FILE_SELECTED_IPC';
export const ALIGNMENT_EXAMPLE_FILES_GET_IPC = 'ALIGNMENT_EXAMPLE_FILES_GET_IPC';
export const ALIGNMENT_EXAMPLE_FILES_GOT_IPC = 'ALIGNMENT_EXAMPLE_FILES_GOT_IPC';
export const ALIGNMENT_SELECT_IPC = 'ALIGNMENT_SELECT_IPC';
export const ALIGNMENT_SELECTED_IPC = 'ALIGNMENT_SELECTED_IPC';
export const ALIGNMENT_ADDED_IPC = 'ALIGNMENT_ADDED_IPC';
export const ALIGNMENTS_ADDED_IPC = 'ALIGNMENTS_ADDED_IPC';
export const PARSING_START_IPC = 'PARSING_START_IPC';
export const PARSING_PROGRESS_IPC = 'PARSING_PROGRESS_IPC';
export const PARSING_END_IPC = 'PARSING_END_IPC';
export const PARSING_ERROR_IPC = 'PARSING_ERROR_IPC';
export const TYPECHECKING_START_IPC = 'TYPECHECKING_START_IPC';
export const TYPECHECKING_PROGRESS_IPC = 'TYPECHECKING_PROGRESS_IPC';
export const TYPECHECKING_END_IPC = 'TYPECHECKING_END_IPC';
export const TYPECHECKING_ERROR_IPC = 'TYPECHECKING_ERROR_IPC';
export const CHECKRUN_START_IPC = 'CHECKRUN_START_IPC';
export const CHECKRUN_END_IPC = 'CHECKRUN_END_IPC';
export const CHECKRUN_ERROR_IPC = 'CHECKRUN_ERROR_IPC';
export const RUN_PROPOSED_IPC = 'RUN_PROPOSED_IPC';
export const RUN_CREATED_IPC = 'RUN_CREATED_IPC';
export const RUN_START_IPC = 'RUN_START_IPC';
export const FLAGSRUN_PROGRESS_IPC = 'FLAGSRUN_PROGRESS_IPC';
export const FLAGSRUN_END_IPC = 'FLAGSRUN_END_IPC';
export const FLAGSRUN_ERROR_IPC = 'FLAGSRUN_ERROR_IPC';
export const CALCULATION_START_IPC = 'CALCULATION_START_IPC';
export const CALCULATION_PROGRESS_IPC = 'CALCULATION_PROGRESS_IPC';
export const CALCULATION_END_IPC = 'CALCULATION_END_IPC';
export const CALCULATION_ERROR_IPC = 'CALCULATION_ERROR_IPC';
export const CALCULATION_CANCEL_IPC = 'CALCULATION_CANCEL_IPC';
export const CALCULATION_CANCELED_IPC = 'CALCULATION_CANCELED_IPC';
