/*
    Strings for ipc
*/
export const OUTPUT_DIR_SELECT = 'OUTPUT_DIR_SELECT';
export const OUTPUT_DIR_SELECTED = 'OUTPUT_DIR_SELECTED';
export const TREE_SELECT = 'TREE_SELECT';
export const TREE_SELECTED = 'TREE_SELECTED';
export const RUN_START = 'RUN_START';
export const RUN_STARTED = 'RUN_STARTED';
export const RUN_STDOUT = 'RUN_STDOUT';
export const RUN_STDERR = 'RUN_STDERR';
export const RUN_FINISHED = 'RUN_FINISHED';
export const RUN_ERROR = 'RUN_ERROR';
export const RUN_CANCEL = 'RUN_CANCEL';
export const FILE_OPEN = 'FILE_OPEN';
export const FILE_SHOW_IN_FOLDER = 'FILE_SHOW_IN_FOLDER';
export const FOLDER_OPEN = 'FOLDER_OPEN';
export const OUTPUT_CHECK = 'OUTPUT_CHECK';
export const OUTPUT_CHECKED = 'OUTPUT_CHECKED';
export const ALIGNMENT_SELECT = 'ALIGNMENT_SELECT';
export const ALIGNMENT_SELECTED = 'ALIGNMENT_SELECTED';
export const ALIGNMENT_PARSE_REQUEST = 'ALIGNMENT_PARSE_REQUEST';
export const ALIGNMENT_PARSE_SUCCESS = 'ALIGNMENT_PARSE_SUCCESS';
export const ALIGNMENT_PARSE_FAILURE = 'ALIGNMENT_PARSE_FAILURE';
export const ALIGNMENT_PARSE_CHANGED_PATH = 'ALIGNMENT_PARSE_CHANGED_PATH';
export const ALIGNMENT_EXAMPLE_FILES_GET_REQUEST = 'ALIGNMENT_EXAMPLE_FILES_GET_REQUEST';
export const ALIGNMENT_EXAMPLE_FILES_GET_SUCCESS = 'ALIGNMENT_EXAMPLE_FILES_GET_SUCCESS';
export const UNHANDLED_ERROR = 'UNHANDLED_ERROR';
export const TOGGLE_BACKBONE_CONSTRAINT = 'TOGGLE_BACKBONE_CONSTRAINT';
export const TOGGLE_MULTIFURCATING_CONSTRAINT = 'TOGGLE_MULTIFURCATING_CONSTRAINT';
export const ADD_RUN = 'ADD_RUN';
export const REMOVE_RUN = 'REMOVE_RUN';
