name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install deps
        run: yarn

      - name: Download binaries
        run: npm run download-binaries

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          # macOS notarization API key
          APPLEID: ${{ secrets.apple_id }}
          APPLEIDPASS: ${{ secrets.apple_id_pass }}
          APPLEIDTEAM: ${{ secrets.apple_id_team }}
          SENTRY_URL: ${{ secrets.sentry_url }}
          SENTRY_ORG: ${{ secrets.sentry_org }}
          SENTRY_PROJECT: ${{ secrets.sentry_project }}
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
